### ISSUE TITLE
How do I use mod_geomap in a project I created with cowboy?

### ISSUE THREAD

**Issue by leeyisoft** [zotonic/mod_geomap#6]
How do I use mod_geomap in a project I created with cowboy ( https://github.com/imboy-pub/imboy )?

I know how to use Redis GEO. Is mod_geomap similar in function to Redis GEO? Is there any documentation on how to access other projects?

**Comment by mworrell** [comment]
Hi, mod_geomap is a module for Zotonic 0.x.

For Zotonic 1.x we have [zotonic_mod_geomap](https://github.com/zotonic/zotonic_mod_geomap).  Zotonic 1.x is Cowboy based but uses its own dispatcher and cow machine for the controllers.

Both need their Zotonic version and are not directly for use in non-Zotonic projects.

**Comment by mworrell** [comment]
Closing for now, you can reopen if you have more questions.
